version: '3'

services:
  mailhog:
    image: mailhog/mailhog
    ports: 
     - 1025:1025
     - 8025:8025
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.mailhog.rule=Host(`mailhog.docker.localhost`)"
      - "traefik.http.routers.mailhog.tls=true"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
