services:
  minica:
    container_name: minica
    image: ghcr.io/bjornsnoen/minica-traefik-api:latest
    volumes:
      - ./certificates:/app/certificates
      - /var/run/:/var/run/
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
      DOCKER_LISTEN: "yes"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minica.rule=Host(`minica.localhost`)"
      - "traefik.http.routers.minica.tls=true"

  traefik:
    container_name: traefik
    image: traefik:v2.5
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--providers.file.directory=/app/certificates"
    volumes:
      - /var/run/:/var/run/
      - ./certificates:/app/certificates
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefiksecure.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.traefiksecure.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      - proxy

networks:
  proxy:
    external: true