version: "3.3"

services:
    php:
        container_name: php-${APP_NAME}
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - proxy
        volumes:
            - ./src:/var/www/html
    nginx:
        container_name: nginx-${APP_NAME}
        image: nginx:stable-alpine
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.docker.localhost`)"
            - "traefik.http.routers.${APP_NAME}.tls=true"
        networks:
            - proxy
        environment:
            APP_NAME: ${APP_NAME}
        volumes:
            - ./src:/var/www/html
            - ./.docker/nginx/logs:/var/log/nginx
            - ./.docker/nginx/conf:/etc/nginx/templates
        depends_on:
            - php

networks:
  proxy:
    external: true