version: '3'

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - discovery.type=single-node
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.elasticsearch.rule=Host(`elasticsearch.localhost`)"
      - "traefik.http.routers.elasticsearch.tls=true"
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true