version: '3.7'

services:
  mysql57:
    image: mysql:5.7
    container_name: mysql57
    volumes:
      - mysql57-data:/var/lib/mysql
    networks:
      - proxy
      - default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

volumes:
  mysql57-data:
    name: mysql57-data

networks:
  proxy:
    external: true