version: '3.7'

services:
  mysql57:
    image: mysql:5.7
    container_name: mysql57
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
      - ./logs/slow-query.log:/var/log/mysql/slow-query.log
    networks:
      - proxy
      - default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

networks:
  proxy:
    external: true