services:
    php:
        container_name: ${APP_NAME}-php
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - proxy
        extra_hosts:
            - ${APP_NAME}.localhost:172.17.0.1
        volumes:
            - ./src:/var/www/html
            - ./.docker/php/logs:/var/log/php-fpm
            - ./.docker/xdebug/xdebug.log:/var/log/xdebug.log
            - ./.docker/xdebug/profile:/tmp/xdebug/profile
            - ./.docker/xdebug/trace:/tmp/xdebug/trace
            - ./.docker/xdebug/coverage:/tmp/xdebug/coverage

    nginx:
        container_name: ${APP_NAME}-nginx
        image: nginx:stable-alpine
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.localhost`)"
#            - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.localhost`) || Host(`subdomain1.${APP_NAME}.localhost`) || Host(`subdomain2.${APP_NAME}.localhost`)"
            - "traefik.http.routers.${APP_NAME}.tls=true"
        networks:
            - proxy
        volumes:
            - ./src:/var/www/html
            - ./.docker/nginx/logs:/var/log/nginx
            - ./.docker/nginx/conf:/etc/nginx/templates
        environment:
            APP_NAME: ${APP_NAME}

#    httpd:
#        container_name: ${APP_NAME}-httpd
#        image: httpd:latest
#        networks:
#            - proxy
#        volumes:
#            - ./src:/var/www/html
#            - ./.docker/httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
#            - ./.docker/httpd/conf/sites-enabled:/usr/local/apache2/sites-enabled
#            - ./.docker/httpd/logs:/usr/local/apache2/logs
#        labels:
#            - "traefik.enable=true"
#            - "traefik.docker.network=proxy"
#            - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.localhost`)"
##            - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.localhost`) || Host(`subdomain1.${APP_NAME}.localhost`) || Host(`subdomain2.${APP_NAME}.localhost`)"
#            - "traefik.http.routers.${APP_NAME}.tls=true"
#        environment:
#            APP_NAME: ${APP_NAME}

#    mysql:
#        container_name: ${APP_NAME}-mysql
#        image: mysql:8
#        volumes:
#            - ./.docker/mysql/data:/var/lib/mysql
#            - ./.docker/mysql/dumps:/home/dumps
#            - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
#            - ./.docker/mysql/logs/slow-query.log:/var/log/mysql/slow-query.log
#        networks:
#            - proxy
#        environment:
#            MYSQL_ROOT_PASSWORD: root
#        ports:
#            - ${DB_PORT}:3306

networks:
    proxy:
        external: true