version: '3.7'

services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    volumes:
      - ./data:/var/lib/mysql
      - ./dumps:/home/dumps
      - ./my.cnf:/etc/mysql/my.cnf
      - ./logs/slow-query.log:/var/log/mysql/slow-query.log
    networks:
      - proxy
      - default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

networks:
  proxy:
    external: true